name: Deploy VitePress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node 环境
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 启用 pnpm
      - name: Enable pnpm
        run: corepack enable

      # 4. 安装依赖（根目录）
      - name: Install dependencies
        run: pnpm install

      # 5. 构建（注意：docs）
      - name: Build site
        run: pnpm run docs:build

      # 6. 上传 dist 到服务器
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docs/.vitepress/dist/*"
          target: "/var/www/main"
